SELECT *
FROM TB_TODO;


INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(1,'테스트1','테스트1 입니다.',1,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(2,'테스트2','테스트2 입니다.',0,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(3,'테스트3','테스트3 입니다.',0,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(4,'테스트4','테스트4 입니다.',0,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(5,'테스트5','테스트5 입니다.',0,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(6,'테스트6','테스트6 입니다.',0,SYSDATE);

INSERT INTO TB_TODO(TODO_NO,TODO_TITLE,TODO_DETAIL,TODO_COMPLETE,REG_DATE)
VALUES(7,'테스트7','테스트7 입니다.',0,SYSDATE);

COMMIT;

ROLLBACK;

DELETE 
FROM TB_TODO;

