SELECT MEMBER_ID  AS 아이디,
			MEMBER_NAME  AS 이름,
			MEMEBR_PWD AS  비밀번호,
			GRADE_NAME AS  등급명,
			AREA_NAME AS 지역명
			
FROM TB_MEMBER M
JOIN TB_GRADE ON (GRADE_CODE = GRADE)
JOIN TB_AREA USING(AREA_CODE)

WHERE 
 (GRADE, AREA_CODE) = (
	 SELECT GRADE,AREA_CODE     -- GRADE와 AREA_CODE 컬럼을 조회
	 FROM TB_MEMBER       		 			-- TB_MEMBER 테이블에서
	 WHERE MEMBER_ID LIKE '%1234%'  )
ORDER BY 아이디 DESC;


-- 아이디에 1234가 포함되는 회원과
-- 같은 등급, 같은지역인 회원들의 아이디, 비밀번호, 이름, 등급명, 지역명을 아이디 내림차순으로 조회
-- 문제 원인1 : SELECT 절에 AREA_NAME





SELECT
	MEMBER_ID AS 아이디,
	MEMEBR_PWD 비밀번호,
	MEMBER_NAME AS 이름,
	GRADE_NAME AS 등급명,
	AREA_NAME 지역명
FROM
	TB_MEMBER
-- JOIN TB_GRADE		USING(GRADE_CODE)
JOIN TB_GRADE ON (GRADE_CODE = GRADE)
JOIN TB_AREA USING(AREA_CODE)

WHERE (GRADE,AREA_CODE) = (
	SELECT GRADE,AREA_CODE
	FROM TB_MEMBER
--WHERE MEMBER_ID = '1234'
		WHERE MEMBER_ID LIKE '%1234%')
ORDER BY MEMBER_ID DESC;